# Generated by Django 2.1.3 on 2018-12-06 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ustatus', models.CharField(blank=True, default='0000000', max_length=30)),
                ('ucont', jsonfield.fields.JSONField(blank=True, default='{}')),
                ('uconfigs', jsonfield.fields.JSONField(blank=True, default='{}')),
                ('template01', models.TextField(blank=True, default='Template 01 Is Empty!')),
                ('template02', models.TextField(blank=True, default='Template 02 Is Empty!')),
                ('template03', models.TextField(blank=True, default='Template 03 Is Empty!')),
                ('template04', models.TextField(blank=True, default='Template 04 Is Empty!')),
                ('template05', models.TextField(blank=True, default='Template 05 Is Empty!')),
                ('template06', models.TextField(blank=True, default='Template 06 Is Empty!')),
                ('template07', models.TextField(blank=True, default='Template 07 Is Empty!')),
                ('template08', models.TextField(blank=True, default='Template 08 Is Empty!')),
                ('template09', models.TextField(blank=True, default='Template 09 Is Empty!')),
                ('template10', models.TextField(blank=True, default='Template 10 Is Empty!')),
                ('noresptemplate01', models.TextField(blank=True, default='No Response Template 01 Is Empty!')),
                ('noresptemplate02', models.TextField(blank=True, default='No Response Template 02 Is Empty!')),
                ('noresptemplate03', models.TextField(blank=True, default='No Response Template 03 Is Empty!')),
                ('noresptemplate04', models.TextField(blank=True, default='No Response Template 04 Is Empty!')),
                ('noresptemplate05', models.TextField(blank=True, default='No Response Template 05  Is Empty!')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
