# Generated by Django 2.1.3 on 2018-12-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ustatus',
        ),
    ]
