# Generated by Django 2.1.3 on 2018-12-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_profile_ustatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uconfigs',
            new_name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='0000000', max_length=30),
        ),
    ]
