# Generated by Django 2.1.3 on 2018-12-06 20:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20181207_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uconfig',
            field=jsonfield.fields.JSONField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='0000000'),
        ),
    ]
