# Generated by Django 2.1.3 on 2018-12-06 20:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20181207_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uconfig',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ucont',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
